name: "Build"
on: [push, pull_request]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
        with:
          submodules: recursive
      - name: "Build"
        uses: docker://josejulio/hypha-builder:release_1.7.x
        with:
          entrypoint: " "
          args: " -j2 CTEST_OUTPUT_ON_FAILURE=1 VERBOSE=1 all test"
        env:
          CODE: "/github/workspace/"
          PATCH_WASM_LD: "1"
